FROM ruby:2.7.4-bullseye

WORKDIR '/apps/bank_api'

COPY ./Gemfile .
COPY ./Gemfile.lock .

EXPOSE 3000

RUN apt-get update -qq -y

RUN apt-get install sqlite3 -y

RUN apt-get install -y build-essential libpq-dev nodejs npm

RUN npm install --global yarn

RUN gem install rails bundler

RUN gem install rails -v '7.0.2'

RUN bundle install

# Add a script to be executed every time the container starts.
# COPY entrypoint.sh /usr/bin/
# RUN chmod +x /usr/bin/entrypoint.sh
# ENTRYPOINT ["entrypoint.sh"]

CMD ["rails", "server", "-b", "0.0.0.0"]