default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("PUMA_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgres
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  schema_search_path: "bank, public"

test:
  <<: *default
  database: postgres
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  schema_search_path: "bank, public"
