default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("PUMA_MAX_THREADS") { 5 } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: exam
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  schema_search_path: "bank, public"

test:
  <<: *default
  database: exam_test
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  schema_search_path: "bank, public"
